name: arifinajib
favicon: null
layout_spectrum: 0.8635523761622608
typography_spectrum: 0.64994
title: arifin ajib
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#909d8c'
    - '#2f5c61'
    - '#eee5d5'
    - '#aeca53'
    - '#934c42'
  brandStrength: 0.14281016099266708
  lightness: 0.043111710576340556
  saturation: 0.24189843540079892
  rhythmicContrast: 0.4252836036030203
purpose: []
